### ISSUE TITLE
Dependecy magnagment and Package building.

### ISSUE THREAD

**Issue by Borg93** [Swedish-National-Archives-AI-lab/htrflow_core#10]
https://github.com/Swedish-National-Archives-AI-lab/htrflow_core/blob/28fe97de5607f645f1486d45f9225c2dc844c750/pyproject.toml#L1

- Hatch vs Poetry --> do the implementation
- Update toml and call to a demo meeting showcasing the solution for dependecy magnagment and package building.

General concerns to think about
- pip and conda
- Cuda versioning and Pytorch
- Perhaps docker?

**Comment by VivRibbon** [comment]
Working on this now.
